#!/usr/bin/env bash
# forbidden-check.sh — grep i termini proibiti dalla skill /relazione
# Usage: forbidden-check.sh <file.md|file.tex> [--brand <nome>] [--user-profile]
# Exit: 0 = clean, 1 = found violations
set -euo pipefail

FILE=""
BRAND=""
USER_PROFILE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --brand) BRAND="$2"; shift 2 ;;
    --user-profile) USER_PROFILE=1; shift ;;
    -h|--help) echo "Usage: $0 <file> [--brand <nome>] [--user-profile]"; exit 0 ;;
    *) if [ -z "$FILE" ]; then FILE="$1"; fi; shift ;;
  esac
done

if [ -z "$FILE" ]; then
  echo "Usage: $0 <file> [--brand <nome>] [--user-profile]" >&2
  exit 2
fi
if [ ! -f "$FILE" ]; then
  echo "ERROR: file not found: $FILE" >&2
  exit 2
fi

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

FOUND=0

run_check() {
  local label="$1"
  local pattern="$2"
  local matches
  matches=$(grep -nEi "$pattern" "$FILE" || true)
  if [ -n "$matches" ]; then
    echo ""
    echo "[$label]"
    echo "$matches"
    FOUND=1
  fi
}

# 1. AI system references
run_check "AI-REF" "Claude|Anthropic|Sonnet|Opus|Haiku|GPT|OpenAI|Gemini|Mistral|Llama|Cohere|DeepSeek|LLM"
run_check "AI-DISCLAIMER" "🤖 Generated|Co-Authored-By: Claude|Generated with Claude Code|generato (con|da) (intelligenza artificiale|AI|Claude)|AI-(generated|assisted)"
run_check "AI-META" "Come AI|In qualità di assistente|As an AI|I am an AI|I was asked to write|come modello linguistico|chatbot"

# 2. AI tells IT
run_check "AI-TELL-IT" "in conclusione|rappresenta una pietra miliare|navigare nel complesso panorama|in un'epoca caratterizzata|garantire un'esperienza ottimale|in un mondo sempre più (digitale|connesso)|abbracciare il cambiamento|fondamentalmente"

# 3. AI tells EN
run_check "AI-TELL-EN" "delve into|tapestry of|in conclusion|it is worth noting|navigate the complex landscape|in the realm of|embark on a journey|stands as a testament|in today's digital age|seamlessly"

# 3b. AI tells ES
run_check "AI-TELL-ES" "en el ámbito de|representa un hito|navegar el complejo panorama|en un mundo cada vez más|en conclusión,|adentrarse en"

# 3c. AI tells FR
run_check "AI-TELL-FR" "s'inscrit dans|représente un jalon|naviguer dans le paysage complexe|en conclusion,|dans un monde de plus en plus|il convient de noter"

# 3d. AI tells DE
run_check "AI-TELL-DE" "stellt einen Meilenstein dar|im heutigen digitalen Zeitalter|navigieren durch die komplexe Landschaft|abschließend lässt sich|in einer zunehmend"

# 3e. AI tells PT
run_check "AI-TELL-PT" "representa um marco|navegar no complexo panorama|em conclusão,|num mundo cada vez mais|vale ressaltar"

# 4. LaTeX comments mentioning AI
run_check "LATEX-COMMENT-AI" "^%.*( AI | Claude | Anthropic |generated automatically|generated by AI)"

# 5. Brand banned_words (da .brand-profile.json, attivato con --brand)
if [ -n "$BRAND" ] && [ -f "$SKILL_DIR/.brand-profile.json" ] && command -v python3 >/dev/null 2>&1; then
  BRAND_WORDS=$(python3 -c "
import json, sys
try:
    with open(r'$SKILL_DIR/.brand-profile.json') as f:
        bp = json.load(f)
    for b in bp.get('brands', []):
        if b.get('nome') == '$BRAND':
            for w in b.get('banned_words', []):
                print(w)
            break
except Exception as e:
    sys.exit(0)
" 2>/dev/null || true)
  if [ -n "$BRAND_WORDS" ]; then
    PATTERN=$(echo "$BRAND_WORDS" | awk 'NF' | paste -sd'|' -)
    [ -n "$PATTERN" ] && run_check "BRAND-BANNED [$BRAND]" "$PATTERN"
  fi
fi

# 6. User banned_words (da .user-profile.json, attivato con --user-profile)
if [ $USER_PROFILE -eq 1 ] && [ -f "$SKILL_DIR/.user-profile.json" ] && command -v python3 >/dev/null 2>&1; then
  USER_WORDS=$(python3 -c "
import json, sys
try:
    with open(r'$SKILL_DIR/.user-profile.json') as f:
        up = json.load(f)
    for w in up.get('banned_words', []):
        print(w)
except Exception as e:
    sys.exit(0)
" 2>/dev/null || true)
  if [ -n "$USER_WORDS" ]; then
    PATTERN=$(echo "$USER_WORDS" | awk 'NF' | paste -sd'|' -)
    [ -n "$PATTERN" ] && run_check "USER-BANNED" "$PATTERN"
  fi
fi

if [ $FOUND -eq 0 ]; then
  echo "OK: no forbidden terms found in $FILE"
  exit 0
else
  echo ""
  echo "FAIL: forbidden terms detected in $FILE — riscrivi prima di consegnare"
  exit 1
fi
